version: '3.1'
services:
  db:
    image: postgres
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  web:
    image: python_flask_image
    build: ./python
    restart: always
    environment:
      FLASK_APP: app.py
    ports:
      - "8000:5000"
    volumes:
      - ./python:/usr/src/app

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
